"""empty message

Revision ID: 33c44abc0719
Revises: ff0bf7b3b5d8
Create Date: 2025-04-16 16:44:29.837166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c44abc0719'
down_revision = 'ff0bf7b3b5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('caption', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created')
        batch_op.drop_column('caption')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
