"""empty message

Revision ID: 619d876ce0cd
Revises: c18a8f59a2e6
Create Date: 2025-04-16 19:25:32.707774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619d876ce0cd'
down_revision = 'c18a8f59a2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post__tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post__tag')
    # ### end Alembic commands ###
