"""empty message

Revision ID: 778fd5842a44
Revises: b3a1768b9caa
Create Date: 2025-04-16 17:16:36.801451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778fd5842a44'
down_revision = 'b3a1768b9caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=270), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
