"""empty message

Revision ID: c18a8f59a2e6
Revises: 284f42a97fce
Create Date: 2025-04-16 19:22:42.216530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18a8f59a2e6'
down_revision = '284f42a97fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name='post_tag_pkey')
    )
    # ### end Alembic commands ###
